### ISSUE TITLE
react 0.13.1 compatibility

### ISSUE THREAD

**Issue by berndca** [TuxedoJS/TuxedoJS#166]
It appears that some changes in react 0.13 around ctor and componentWillMount are breaking the "nearestOwnerProps" in Tuxx. The mixin TuxxPropTypeCheckerMixin.js issues an exception because this.nearestOwnerProps is undefined. I'm using the Tuxx Chat App example code. As a workaround to #165 changed all react-router related code to use react-router directly and deleted the Tuxx/Router directory.

Do you plan to make Tuxx compatible with react 0.13?

Thanks, Bernd

**Comment by Cheerazar** [comment]
Thank you for pointing out the issues. I'll start working on updating Tuxx to work with react 0.13 and the associated react-router changes.

**Comment by Cheerazar** [comment]
This has been fixed in commit 13a234af8bd9c04adeb01a4948c71229f21f5117.
